import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Provider from "@/components/Hoc/Provider";

const font = Inter({
  weight: ['100','200','300','400','500','600','700','800','900'] , 
  subsets : ['latin'],
})

export const metadata: Metadata = {
  title: "Vikas Gurjar Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${font.className}antialiased`}
      >
        
        <Provider>{children}</Provider>
        
      </body>
    </html>
  );
}
